root = "."
tmp_dir = "build"

[build]
  bin = "./build/main"
  cmd = "templ generate && go build -o ./build/main ./cmd/htd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "web/node_modules"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["views", "web", "cmd", "pkg"]
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "ts"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
