
CREATE TABLE IF NOT EXISTS products(
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  brand TEXT NOT NULL,
  category TEXT NOT NULL,
  sku TEXT NOT NULL,
  price REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS images(
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  alt TEXT NOT NULL,
  type TEXT NOT NULL,
  path TEXT NOT NULL
);
